fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true
            template: FOSUserBundle:Registration:email.txt.twig
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: FOSUserBundle:Resetting:email.txt.twig
    from_email:
        address: "contact@qaam.fr"
        sender_name: "contact@qaam.fr"