security:
    access_denied_url: /login

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            host: api\.qaam\.fr
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        auth_register:
            host: api\.qaam\.fr
            pattern: ^/auth/register
            stateless: true
            anonymous: true
            provider: fos_userbundle

        api:
            host: api\.qaam\.fr
            pattern: ^/
            stateless: true
            anonymous: false
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            host: admin\.qaam\.fr
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:    true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.qaam\.fr }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.qaam\.fr }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.qaam\.fr }
        - { path: ^/redirectionTo, role: IS_AUTHENTICATED_FULLY, host: admin\.qaam\.fr }
        - { path: ^/, role: ROLE_ADMIN, host: admin\.qaam\.fr }


