swiftmailer:
    delivery_addresses: ['fernandezjeanphilippe@gmail.com']
    transport: smtp
    encryption: ssl
    host: smtp.gmail.com
    username: fernandezjeanphilippe@gmail.com
    password: Tqbhf7328zd
    spool: { type: 'memory' }
