controllers:
    host: 'QAAM.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.QAAM.fr'
    path: /login_check
    methods: [POST]

api_controllers:
    host: 'api.QAAM.fr'
    resource: ../../src/ApiController/
    type: annotation
