# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    image_abs_path: '%kernel.project_dir%/public/uploads/img-task'
    image_path: '/uploads/img-task'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    circular_reference_handler:
        public: false
        class: callback
        factory: [App\Serializer\CircularHandlerFactory, getId]

    serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        arguments: ["@serializer.mapping.class_metadata_factory", null, "@serializer.property_accessor"]
        public: false
        tags: [serializer.normalizer]
        calls:
            - method: setCircularReferenceLimit
              arguments: [1]
            - method: setCircularReferenceHandler
              arguments: ["@circular_reference_handler"]

    form.type.model.listitemType:
        class: App\Form\ListitemType
        arguments: ["@doctrine.orm.entity_manager"]

    FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer.twig_swift'

    app.registration_listener:
        class: App\EventListener\RegisterConfirmationListener
        arguments: ["@fos_user.mailer.twig_swift", "@fos_user.util.token_generator", '@session']
        tags:
            - { name: kernel.event_subscriber }

    app.form.registration:
        class: App\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    controller.user:
        class: App\Controller\UserController
        arguments: ["@fos_user.user_manager"]

    fos_user.password_resetting:
        class: App\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
